name: 4dgs
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - torchmetrics 
  - ninja
  - plyfile
  - python=3.10
  - tqdm 
  - imagesize
  - kornia
  - omegaconf
  - pynput
  - pyparsing
  - matplotlib
  - ffmpeg
  - pip:
    - ./simple-knn --no-build-isolation
    - ./pointops2 --no-build-isolation
    - torch torchvision --index-url https://download.pytorch.org/whl/cu130