name: 4dgs
channels:
  - defaults
dependencies:
  - pip
  - torchmetrics 
  - ninja
#  - plyfile
  - pybind11
  - tqdm 
  - imagesize
#  - omegaconf
#  - pynput
  - pyparsing
  - matplotlib
  - python=3.13
  - ffmpeg
  - pytorch=2.12
  - torchvision
  - cuda-version=13.0
  - pip:
    - kornia
    - omegaconf
    - plyfile
    - pynput
    - safetensors
##    - ./simple-knn --no-build-isolation
#    - ./pointops2 --no-build-isolation
#    - torch torchvision --index-url https://download.pytorch.org/whl/cu130
